apiVersion: v2
appVersion: auto
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 6.6.1
deprecated: false
description: "Collabora Online Development Edition \u2013 an awesome, Online Office\
  \ suite image suitable for home use."
home: https://github.com/truecharts/apps/tree/master/charts/stable/collabora-online
icon: https://truecharts.org/_static/img/collabora-icon.png
keywords:
- collabora-online
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: stavros-k@users.noreply.github.com
  name: stavros-k
  url: truecharts.org
name: collabora-online
sources:
- https://hub.docker.com/r/collabora/code
- https://sdk.collaboraonline.com/contents.html
- https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm
type: application
version: 6.4.1
